/* scripts/data.js — 学园样例数据 */
window.GameData = (function () {

  // —— 设施 —— //
  const facilities = [
    { id: 'fac-old-lib', name: '旧馆图书室', type: '学术', area: '本馆 · 三层西翼', desc: '木质长椅与铁艺楼梯，光线斜照下尘埃如银粉飘落。', tone: 'sakura',
      hours: '周一至周六 08:00 — 20:30',
      atmosphere: '安静、墨香、被翻旧的诗页',
      orgs: ['org-lit-club', 'org-disciplinary'],
      icon: 'book' },
    { id: 'fac-school-court', name: '中央庭园', type: '休憩', area: '主楼 · 中庭', desc: '环抱式回廊与樱花并植，春末花瓣会铺成粉色的小径。', tone: 'wisteria',
      hours: '全时段开放（夜间限照明区）',
      atmosphere: '风、铜铃、樱、远处的钢琴声',
      orgs: ['org-student-council', 'org-photo-club'],
      icon: 'leaf' },
    { id: 'fac-music-hall', name: '梧桐音乐厅', type: '艺术', area: '艺术楼 · 一层', desc: '曾是老校长的私人演奏室，至今保留着一架斯坦威立式钢琴。', tone: 'amber',
      hours: '周二、周四 14:00 — 18:00',
      atmosphere: '微微的松香、回响、踏板低鸣',
      orgs: ['org-orchestra', 'org-vocal-club'],
      icon: 'music' },
    { id: 'fac-gymnasium', name: '第一体育馆', type: '运动', area: '运动场 · 北馆', desc: '高耸的拱顶、悬挂的横幅，地板被几代人擦得发亮。', tone: 'moss',
      hours: '周一至周日 06:00 — 22:00',
      atmosphere: '汗水、塑胶、口哨、远处的回响',
      orgs: ['org-basketball', 'org-disciplinary'],
      icon: 'activity' },
    { id: 'fac-cafe', name: '云雀咖啡间', type: '休憩', area: '学生会馆 · 二层', desc: '半开放阁楼，飘着现磨咖啡和柠檬蛋糕的甜味。', tone: 'amber',
      hours: '周一至周五 12:00 — 18:30',
      atmosphere: '焦糖、低语、磨豆机的嗡鸣',
      orgs: ['org-student-council', 'org-photo-club'],
      icon: 'coffee' },
    { id: 'fac-shrine', name: '校园神社', type: '信仰', area: '后山 · 樱径尽头', desc: '朱漆鸟居略有斑驳，奉祀学业之神。绘马板挂满了愿望。', tone: 'vermil',
      hours: '常年 · 凌晨封山',
      atmosphere: '檀香、风铃、落叶踩脆',
      orgs: ['org-tea-ceremony'],
      icon: 'flame' },
    { id: 'fac-darkroom', name: '银盐暗房', type: '艺术', area: '艺术楼 · 地下一层', desc: '红灯下显影液的微酸刺鼻，墙上夹满了未风干的人像。', tone: 'vermil',
      hours: '周三、周五 16:00 — 20:00',
      atmosphere: '化学、暗红、慢节拍的呼吸',
      orgs: ['org-photo-club'],
      icon: 'palette' },
    { id: 'fac-clubhouse', name: '部活栋', type: '综合', area: '校东 · 独立三层楼', desc: '每个房间一种气味，每条走廊都贴着部活的招新海报。', tone: 'wisteria',
      hours: '周一至周日 13:00 — 21:00',
      atmosphere: '木地板、贴纸、午后的喧闹',
      orgs: ['org-lit-club', 'org-orchestra', 'org-vocal-club', 'org-basketball', 'org-photo-club', 'org-tea-ceremony'],
      icon: 'door-open' },
    { id: 'fac-greenhouse', name: '玻璃温室', type: '生物', area: '理化楼 · 顶层连廊', desc: '热带蕨与石楠在玻璃下生长，空气里悬着雾。', tone: 'moss',
      hours: '周一至周六 09:00 — 17:00',
      atmosphere: '潮湿、绿、远处的滴水',
      orgs: ['org-biology'],
      icon: 'seedling' },
    { id: 'fac-rooftop', name: '钟楼天台', type: '休憩', area: '钟楼 · 顶层', desc: '钟摆每隔一小时敲响。整个学园尽在脚下。', tone: 'sakura',
      hours: '凭学生会通行牌',
      atmosphere: '风、铜锈、远方的城',
      orgs: ['org-student-council'],
      icon: 'flag' },
    { id: 'fac-archives', name: '档案馆', type: '行政', area: '本馆 · 地下一层', desc: '以年份为序排开的金属档案柜，连尘也整齐。', tone: 'ink',
      hours: '凭申请进入',
      atmosphere: '铁锈、纸张、电子荧光',
      orgs: ['org-disciplinary', 'org-student-council'],
      icon: 'archive' },
    { id: 'fac-tearoom', name: '清水茶室', type: '艺术', area: '后山 · 樱径中段', desc: '推拉式障子门内，榻榻米与铸铁壶，水声不止。', tone: 'moss',
      hours: '周二、周四 15:00 — 18:00',
      atmosphere: '抹茶、檀木、茶釜的咕嘟',
      orgs: ['org-tea-ceremony'],
      icon: 'flowerOutline' },
  ];

  // —— 组织 —— //
  const organizations = [
    { id: 'org-student-council', name: '学生会', short: '学生会', tone: 'sakura', icon: 'school',
      lead: '审议 · 审批 · 仲裁',
      desc: '学园的最高自治机构，负责章程审议、活动审批、资源调配与对外协调。',
      tagline: '自治、克己、温柔以待。',
      facility: 'fac-school-court',
      members: ['ch-chinatsu', 'ch-aoi', 'ch-haruki'],
      type: '校级机构',
      tags: ['执行委员会', '审批权', '春樱章'],
      story: '位于中央庭园回廊尽头，会长室的门牌是手刻的桐木匾额。每周一七点的「晨会」从不取消。' },
    { id: 'org-disciplinary', name: '风纪委员会', short: '风纪委', tone: 'vermil', icon: 'shield',
      lead: '巡查 · 仲裁 · 守护',
      desc: '维护校园秩序的执法机关，可随机抽查仪容、夜间巡视、处理纠纷。',
      tagline: '以礼为尺，不取分毫。',
      facility: 'fac-archives',
      members: ['ch-haruki', 'ch-mio'],
      type: '校级机构',
      tags: ['纪律', '巡查证', '夜间通行'],
      story: '风纪委的徽章是一枚青铜小钟，巡查时会发出极细的叮当声，许多学生因这声音而提前整理好衣领。' },
    { id: 'org-lit-club', name: '文学部', short: '文部', tone: 'wisteria', icon: 'feather',
      lead: '阅读 · 撰写 · 同人',
      desc: '由旧馆图书室改建的私邸社团，举办读书会、原创志合本、夜读会。',
      tagline: '于墨色之中遇见自己。',
      facility: 'fac-old-lib',
      members: ['ch-mc', 'ch-aoi', 'ch-ryouko'],
      type: '部活',
      tags: ['同人志', '夜读会', '诗会'],
      story: '部室角落有一个无人认领的旧木抽屉，据说锁着文部初代部长留下的未完结手稿。' },
    { id: 'org-photo-club', name: '影像研究部', short: '影研', tone: 'ink', icon: 'palette',
      lead: '取景 · 显影 · 故事',
      desc: '兼营银盐与数码，提供学园所有大小活动的视觉记录与人像创作。',
      tagline: '凝住一刻，便已是叙事。',
      facility: 'fac-darkroom',
      members: ['ch-yuuna', 'ch-ryouko'],
      type: '部活',
      tags: ['银盐', '展览', '人像'],
      story: '部室的墙上挂着上届部长留下的「七十二个表情」系列，至今每一张都能道出一个人物的故事。' },
    { id: 'org-orchestra', name: '交响乐团', short: '乐团', tone: 'amber', icon: 'music',
      lead: '合奏 · 公演 · 巡回',
      desc: '定期举行的春樱演奏会和秋之夜公演，是学园最大型的艺术活动。',
      tagline: '众音和则群山为之静默。',
      facility: 'fac-music-hall',
      members: ['ch-chinatsu', 'ch-mio'],
      type: '部活',
      tags: ['弦乐', '公演', '巡回'],
      story: '指挥台后挂着代代指挥的肖像，最新的一张是去年毕业的乐团女王。' },
    { id: 'org-vocal-club', name: '声乐社', short: '声乐', tone: 'sakura', icon: 'music',
      lead: '齐唱 · 合声 · 比赛',
      desc: '专攻合唱与小型重唱，每年代表学园出征县联合合唱大赛。',
      tagline: '一人不可独鸣，群音始为歌。',
      facility: 'fac-music-hall',
      members: ['ch-mio'],
      type: '部活',
      tags: ['合唱', '比赛', '夏会'],
      story: '社团传承的曲目簿厚达三厘米，里面记着每一届指定曲与即兴改编。' },
    { id: 'org-basketball', name: '篮球部 · 男女混合', short: '篮球部', tone: 'moss', icon: 'activity',
      lead: '训练 · 联赛 · 集训',
      desc: '常年训练的体育部门，曾连续三年闯入县大会决赛。',
      tagline: '踏地有声，不弃方休。',
      facility: 'fac-gymnasium',
      members: ['ch-haruki', 'ch-yuuna'],
      type: '部活',
      tags: ['县大会', '夏训', '联赛'],
      story: '部室门口那条褪色的「不弃」横幅，是初代部员手书。' },
    { id: 'org-tea-ceremony', name: '清水茶道部', short: '茶道部', tone: 'moss', icon: 'flowerOutline',
      lead: '点前 · 客礼 · 静观',
      desc: '继承学园已逾百年的茶道传承，每月十五日举行例会。',
      tagline: '一期一会，万事勿慌。',
      facility: 'fac-tearoom',
      members: ['ch-chinatsu', 'ch-ryouko'],
      type: '部活',
      tags: ['表千家', '点前', '茶事'],
      story: '茶室存有「百年问箱」，凡入部者将所求之事写在长纸条上投入箱中，毕业之夜方启。' },
    { id: 'org-biology', name: '生物研究部', short: '生研', tone: 'moss', icon: 'seedling',
      lead: '观察 · 培育 · 报告',
      desc: '负责玻璃温室的日常管理，并撰写每月校园生态简报。',
      tagline: '万物生灭皆是诗。',
      facility: 'fac-greenhouse',
      members: ['ch-yuuna'],
      type: '部活',
      tags: ['温室', '生态', '研究志'],
      story: '部室冰箱里偶尔会放着待研究的毛毛虫，请勿误食冰淇淋。' },
  ];

  // —— 角色（花名册） —— //
  const characters = [
    { id: 'ch-mc', name: '主人公（你）', kana: 'YOU', tone: 'ink', avatar: '汝',
      age: 17, year: '高二 · 三组', height: '171 cm',
      orgs: [{ org: 'org-lit-club', role: '部员' }],
      look: '校服规整，左胸口的校徽时时擦亮；银框眼镜后是一双爱观察的眼。',
      build: '中等身形，行走时步幅稳定，仿佛随时能停下来记笔记。',
      wear: '春季制服 · 灰呢西装外套 · 海军蓝领带 · 黑色皮鞋 · 旧背包外侧别着一支钢笔。',
      thoughts: '我倾向于先观察再开口；许多事在我说出来之前已经在心里转了三圈。',
      relations: [
        { who: 'ch-chinatsu', label: '心仪', text: '会长身上有一种「不能轻易触碰」的庄重，但她偶尔的疲惫令我心动。' },
        { who: 'ch-aoi', label: '同部', text: '她爱用诗回应一切，是文部里最不像文部的人。' },
      ],
      special: '左手会无意识转动钢笔。听到雨声会突然走神。',
      tagline: '一个把每一句话都写过两遍的旁观者。' },
    { id: 'ch-chinatsu', name: '一之濑 千夏', kana: 'ICHINOSE Chinatsu', tone: 'sakura', avatar: '千',
      age: 18, year: '高三 · 一组', height: '167 cm',
      orgs: [
        { org: 'org-student-council', role: '会长' },
        { org: 'org-orchestra', role: '小提琴首席' },
        { org: 'org-tea-ceremony', role: '客员' },
      ],
      look: '黑发束成低马尾，一缕碎发常垂落到颈侧；右耳戴一枚极细的银耳钉。',
      build: '修长，肩颈线条干净，因长年练琴而手指尤为漂亮。',
      wear: '校服外套常被披在肩上而非穿好，腰间挂着学生会的青铜钥匙环。',
      thoughts: '我必须先成为「会长」，才能被允许做「千夏」。',
      relations: [
        { who: 'ch-mc', label: '注视', text: '他是少数会安静听我说话的人。这本身就是一种说明。' },
        { who: 'ch-haruki', label: '同僚', text: '春树是我的反面：他直接，我迂回。我们因此互补。' },
        { who: 'ch-mio', label: '后辈', text: '澪在乐团里像一柄锋利的小提琴弓，我必须替她藏好刃。' },
      ],
      special: '深夜会一个人去钟楼天台。喝麦茶不加糖。',
      tagline: '会长不是身份，是她为自己上的锁。' },
    { id: 'ch-aoi', name: '雾岛 葵', kana: 'KIRISHIMA Aoi', tone: 'wisteria', avatar: '葵',
      age: 17, year: '高二 · 三组', height: '162 cm',
      orgs: [
        { org: 'org-student-council', role: '书记' },
        { org: 'org-lit-club', role: '副部长' },
      ],
      look: '及肩中长发常用紫色发夹固定一侧，眉眼像是夏夜被风吹皱的水面。',
      build: '清瘦，喜欢盘腿坐在书架旁。',
      wear: '校服外永远多一件薄羊毛开衫，颜色总是与季节相反。',
      thoughts: '诗只是说话的另一种排列方式。我习惯将真心藏入韵脚。',
      relations: [
        { who: 'ch-mc', label: '同部', text: '我喜欢看他犹豫——那犹豫里有未写完的诗。' },
        { who: 'ch-chinatsu', label: '上司', text: '会长说要交一份月报，她其实想要的不是报告，是确认。' },
      ],
      special: '会随身带一本未署名的笔记本。讨厌大声说话。',
      tagline: '她写下的每一行都像是在让世界放缓一拍。' },
    { id: 'ch-haruki', name: '黑泽 春树', kana: 'KUROSAWA Haruki', tone: 'moss', avatar: '春',
      age: 18, year: '高三 · 二组', height: '180 cm',
      orgs: [
        { org: 'org-disciplinary', role: '委员长' },
        { org: 'org-student-council', role: '常任委员' },
        { org: 'org-basketball', role: '副队长' },
      ],
      look: '短发利落，左眉尾处一条浅疤，是少时打架留下的纪念。',
      build: '挺拔有力，立姿便像在站岗。',
      wear: '风纪委的青铜钟就别在领口下方半寸处，他从不让钟乱响。',
      thoughts: '规则是为了让大家都能放心地犯错。这是我从父亲那里学来的。',
      relations: [
        { who: 'ch-chinatsu', label: '同僚', text: '会长不让我过多卷入，但我能闻出她肩上的重。' },
        { who: 'ch-mio', label: '弟妹', text: '澪是我的远房表妹。她把我看得比自己更重。' },
      ],
      special: '随身常备风纪记录本与一支折叠尺。听到尖叫声会瞬间转身。',
      tagline: '他比规则更冷静，但比规则更愿意低头。' },
    { id: 'ch-mio', name: '黑泽 澪', kana: 'KUROSAWA Mio', tone: 'wisteria', avatar: '澪',
      age: 16, year: '高一 · 二组', height: '156 cm',
      orgs: [
        { org: 'org-disciplinary', role: '一年生委员' },
        { org: 'org-orchestra', role: '中提琴' },
        { org: 'org-vocal-club', role: '声部长' },
      ],
      look: '齐颈短发，左耳一只小银环；眉峰微高，一笑便软。',
      build: '娇小但脚步极快，常被人误认作小学六年级。',
      wear: '校服上别着哥哥送的小铃铛——只有跑步时才听得见。',
      thoughts: '若是被春树哥保护，我永远长不大。所以我加入了风纪委。',
      relations: [
        { who: 'ch-haruki', label: '兄长', text: '他不会承认，但其实最依赖我的是他。' },
        { who: 'ch-chinatsu', label: '尊敬', text: '会长是我抬头时看到的那束光。' },
      ],
      special: '能在五秒内辨认出走廊里的脚步声主人。',
      tagline: '她的小银铃，是哥哥安心的依据。' },
    { id: 'ch-yuuna', name: '汐见 优奈', kana: 'SHIOMI Yuuna', tone: 'amber', avatar: '优',
      age: 17, year: '高二 · 一组', height: '164 cm',
      orgs: [
        { org: 'org-photo-club', role: '部长' },
        { org: 'org-basketball', role: '主力前锋' },
        { org: 'org-biology', role: '兼任研究员' },
      ],
      look: '麦色皮肤，发梢染了一缕焦糖；笑起来眼睛会弯成镰刀状。',
      build: '运动员身材，肩臂有清晰的线条。',
      wear: '常将相机背带斜挎，下衣是改短的运动短裤；夏季会戴薄手套。',
      thoughts: '快门是另一种呼吸。我用它认识世界，世界也用它认识我。',
      relations: [
        { who: 'ch-mc', label: '玩伴', text: '他会成为我下一组人像的主角。' },
        { who: 'ch-ryouko', label: '搭档', text: '凉子是我的暗房之神，没有她就没有我。' },
      ],
      special: '能用嘴衔笔同时打字。下雨天会兴奋。',
      tagline: '她的镜头像猎人。' },
    { id: 'ch-ryouko', name: '若叶 凉子', kana: 'WAKABA Ryouko', tone: 'moss', avatar: '凉',
      age: 17, year: '高二 · 三组', height: '170 cm',
      orgs: [
        { org: 'org-photo-club', role: '副部长 · 暗房负责' },
        { org: 'org-lit-club', role: '部员' },
        { org: 'org-tea-ceremony', role: '点前担当' },
      ],
      look: '亚麻直发垂至背心；圆框眼镜常滑到鼻尖。',
      build: '清癯，立坐之间皆带几分静气。',
      wear: '深绿开衫与校服形成温柔对比；左腕戴一只祖母传下的旧机械表。',
      thoughts: '世界很吵，所以我守住自己的几尺暗房。',
      relations: [
        { who: 'ch-yuuna', label: '搭档', text: '优奈像太阳，但暗房需要月光。' },
        { who: 'ch-aoi', label: '同部', text: '葵的诗，是我最爱阅读的底片。' },
      ],
      special: '能凭气味判断显影剂浓度。茶事时手不抖。',
      tagline: '她的安静里收藏了整个学园的影子。' },
  ];

  // —— 规章文档样例 —— //
  const ruleDocs = [
    { id: 'doc-school-rule', name: '樱栖学园校规（节选）', version: 'v3.2',
      desc: '学园基础行为守则，常驻注入。',
      trigger: 'always', keywords: ['校规', '规定', '违规'],
      injection: 'system', format: 'indent', maxDepth: 2,
      sections: [
        { id: 's1', title: '第一章 总则', children: [
          { id: 's1-1', kind: 'rule', text: '本校以「自治、温柔、克己」为校训，凡入此园者皆当谨守。' },
          { id: 's1-2', kind: 'rule', text: '校规未尽事宜，由学生会与风纪委员会共同议决。' },
        ]},
        { id: 's2', title: '第二章 仪容与衣装', children: [
          { id: 's2-1', kind: 'rule', text: '在校期间须着规定校服。每周三可着便服日，但需遵守仪容标准。' },
          { id: 's2-2', kind: 'rule', text: '不得擅自染发；校服外披穿戴需符合季节规定。' },
          { id: 's2-3', kind: 'rule', text: '配饰应低调，仅允许耳钉一枚以及不超过两枚的戒指。' },
        ]},
        { id: 's3', title: '第三章 部活与社团', children: [
          { id: 's3-1', kind: 'rule', text: '加入新部活须经原部活组织许可与学生会备案。' },
          { id: 's3-2', kind: 'rule', text: '同时归属多组织者，不得使任一组织职责受影响。' },
          { id: 's3-3', kind: 'rule', text: '部活活动费需通过学生会审批后方可使用。' },
        ]},
      ]},
    { id: 'doc-club-charter', name: '文学部社团守则', version: 'v1.4',
      desc: '文学部内部章程，关键词触发注入。',
      trigger: 'keyword', keywords: ['文学部', '同人志', '夜读'],
      injection: 'after', format: 'indent', maxDepth: 3,
      sections: [
        { id: 'l1', title: '第一章 部务', children: [
          { id: 'l1-1', kind: 'rule', text: '部室钥匙由部长保管，副部长与会长各有一副。' },
        ]},
        { id: 'l2', title: '第二章 出版', children: [
          { id: 'l2-1', kind: 'rule', text: '每年合本同人志收录稿件须经全员评议；文负责人为副部长。' },
        ]},
      ]},
  ];

  // —— 申请表样例 —— //
  const formTemplates = [
    {
      id: 'form-club-join', name: '部活加入申请表', code: 'CLUB_JOIN', version: 'v2.1',
      desc: '申请加入新部活时使用，需由原部长（如有）与学生会双重审批。',
      validityDays: 7,
      groups: [
        { id: 'g1', name: '基本信息', fields: [
          { id: 'f1', label: '申请人姓名', type: 'select', required: true,
            source: { kind: 'roster', path: '花名册', display: 'name' },
            placeholder: '从花名册选择' },
          { id: 'f2', label: '所在班级', type: 'text', required: true, placeholder: '如「高二 三组」' },
          { id: 'f3', label: '申请日期', type: 'date', required: true },
        ]},
        { id: 'g2', name: '申请内容', fields: [
          { id: 'f4', label: '欲加入部活', type: 'select', required: true,
            source: { kind: 'organizations', path: '组织名录', display: 'name' },
            placeholder: '选择部活' },
          { id: 'f5', label: '原部活（如有）', type: 'select', required: false,
            source: { kind: 'organizations', path: '组织名录', display: 'name' } },
          { id: 'f6', label: '申请理由', type: 'textarea', required: true,
            min: 30, max: 400, placeholder: '请用至少 30 字阐述加入意愿与可贡献之处。' },
          { id: 'f7', label: '是否参与本期合本', type: 'radio', required: false,
            options: ['是', '否', '视情况而定'] },
        ]},
        { id: 'g3', name: '附加', fields: [
          { id: 'f8', label: '过往作品 / 实绩', type: 'textarea', required: false,
            placeholder: '可粘贴链接或简要描述。' },
          { id: 'f9', label: '本人签字', type: 'text', required: true, placeholder: '请输入您的签名' },
        ]},
      ],
      flow: [
        { id: 's1', name: '原部长审查', who: '原所属部长（如不存在则跳过）', allowReject: true },
        { id: 's2', name: '目标社团审查表格合规性并组织面试', who: '目标社团相关人员', allowReject: true },
        { id: 's3', name: '学生会备案', who: '学生会会长 / 书记', allowReject: true },
      ],
    },
    {
      id: 'form-rooftop', name: '钟楼天台通行申请', code: 'ROOFTOP_PASS', version: 'v1.0',
      desc: '夜间或非授权时段进入钟楼天台所必需的临时通行证申请。',
      validityDays: 1,
      groups: [
        { id: 'g1', name: '基本信息', fields: [
          { id: 'f1', label: '姓名', type: 'select', required: true, source: { kind: 'roster' } },
          { id: 'f2', label: '通行起始时间', type: 'datetime', required: true },
          { id: 'f3', label: '通行截止时间', type: 'datetime', required: true },
        ]},
        { id: 'g2', name: '事由', fields: [
          { id: 'f4', label: '前往原因', type: 'radio', required: true,
            options: ['观星', '取景', '部活活动', '私人事务', '其他'] },
          { id: 'f5', label: '具体说明', type: 'textarea', required: true, min: 20 },
        ]},
      ],
      flow: [
        { id: 's1', name: '风纪委员会审查', who: '风纪委员长', allowReject: true },
        { id: 's2', name: '学生会签发通行证', who: '学生会会长', allowReject: false },
      ],
    },
  ];

  // —— 申请记录（已存在） —— //
  const formRecords = [
    { id: 'rec-1', tplId: 'form-club-join', who: 'ch-mc', applied: '2026-05-22 16:08', status: 'pending', currentStep: 1,
      brief: '申请加入「文学部」夜读分会，欲参与本期合本。' },
    { id: 'rec-2', tplId: 'form-rooftop', who: 'ch-mc', applied: '2026-05-26 14:22', status: 'pending', currentStep: 0,
      brief: '今夜 19:30—21:00 前往钟楼天台观流星。' },
    { id: 'rec-3', tplId: 'form-club-join', who: 'ch-aoi', applied: '2026-04-12 09:14', status: 'approved', currentStep: 3,
      brief: '由学生会备案：葵作为文学部副部长上任。' },
  ];

  // —— 当前激活的世界书条目（上下文注入） —— //
  const worldEntries = [
    { id: 'we-1', name: '旧馆图书室 · 西窗席', tag: '场景', body: '光线斜照，木椅吱呀。这里是文部的非正式聚集地。' },
    { id: 'we-2', name: '一之濑会长', tag: '人物', body: '黑发低马尾、青铜钥匙环。今日略疲。' },
    { id: 'we-3', name: '本周校规重点', tag: '规章', body: '第二章仪容；周三便服日。' },
    { id: 'we-4', name: '春樱演奏会预热', tag: '事件', body: '距演奏会 12 天，乐团排练频次提高。' },
    { id: 'we-5', name: '风纪委青铜钟', tag: '物件', body: '春树常带的钟，发出极细的叮当声。' },
    { id: 'we-6', name: '麦茶（不加糖）', tag: '物件', body: '会长今日在场。' },
    { id: 'we-7', name: '钟楼天台通行', tag: '提示', body: '玩家正在申请，待风纪委审查。' },
  ];

  // —— 课程列表（主角的课表） —— //
  const courses = [
    {
      id: 'c-mod-jp', code: 'JPN-201', name: '近代日本文学选读', kind: 'public', tone: 'sakura',
      teacher: '榊 雪绪', teacherId: '', assistant: '雾岛 葵', assistantId: 'ch-aoi',
      schedule: '周一 / 周三 · 第 3—4 节（10:30—12:00）',
      classroom: '本馆 305 号教室',
      credits: 3, term: '第二学期 · 第 1—16 周',
      brief: '以夏目漱石、芥川龙之介、太宰治三位代表作家为线，串读近代日本叙事的成形与裂变。',
      content: [
        '第 1—4 周：明治维新与文学之觉醒——《吾辈是猫》节选精读。',
        '第 5—8 周：芥川龙之介短篇专题——《罗生门》《地狱变》对比阅读。',
        '第 9—12 周：私小说传统与战后转向——太宰治《人间失格》全本研读。',
        '第 13—16 周：学生分组论文写作与公开讨论会。',
      ],
      midterm: {
        method: '闭卷笔试 + 课堂发表',
        content: '70% 古典语法与文本理解；30% 现场就指定段落进行 5 分钟即兴发表。',
      },
      finalExam: {
        method: '提交学术小论文（3000—4000 字）',
        content: '从三位作家中任选其一，结合时代背景论述其叙事手法之变迁，须引用至少三篇研究文献。',
      },
      remark: '雾岛同学作为助教，每周四下午 16:00—17:00 在文学部部室开放答疑。',
    },
    {
      id: 'c-classic-cn', code: 'CHN-105', name: '古文典藏精读', kind: 'public', tone: 'wisteria',
      teacher: '清水 慎之介', assistant: '——',
      schedule: '周二 · 第 5—6 节（13:30—15:00）',
      classroom: '本馆 211 号教室',
      credits: 2, term: '第二学期 · 全期',
      brief: '从《论语》《史记》到唐宋八大家，体悟汉文典籍的格律与气韵。',
      content: [
        '前八周：先秦诸子选段（《论语》《孟子》《庄子》节选）。',
        '后八周：汉至宋之散文与传记（《史记·项羽本纪》《赤壁赋》等）。',
      ],
      midterm: { method: '默写 + 翻译', content: '指定段落默写 30%，文言译白话 70%。' },
      finalExam: { method: '研究性写作', content: '任选一篇文章撰写不少于 1500 字的赏析。' },
      remark: '清水老师特别强调声读训练，期末加试朗诵小项（不计入总分但记入操行）。',
    },
    {
      id: 'c-math-adv', code: 'MTH-310', name: '高等数学（II）', kind: 'public', tone: 'moss',
      teacher: '远野 真澄', assistant: '若叶 凉子', assistantId: 'ch-ryouko',
      schedule: '周一 / 周四 · 第 1—2 节（08:30—10:00）',
      classroom: '理化楼 102 号教室',
      credits: 4, term: '第二学期 · 第 1—16 周',
      brief: '多元函数微积分、级数与微分方程的系统训练，节奏紧凑。',
      content: [
        '第 1—5 周：多元函数与偏导数 / 全微分。',
        '第 6—9 周：重积分与坐标变换。',
        '第 10—13 周：级数收敛性、傅里叶级数初步。',
        '第 14—16 周：常微分方程与综合应用。',
      ],
      midterm: { method: '闭卷限时 90 分钟', content: '前 8 周内容；解答题为主，含 1 道证明。' },
      finalExam: { method: '闭卷限时 120 分钟', content: '全期内容；含一题开放式建模题。' },
      remark: '若叶助教每周二、五午休时间在理化楼自习室坐镇答疑。',
    },
    {
      id: 'c-eng-debate', code: 'ENG-220', name: '英语辩论与公共表达', kind: 'public', tone: 'amber',
      teacher: 'Eleanor Whitman', assistant: '——',
      schedule: '周五 · 第 7—8 节（15:30—17:00）',
      classroom: '语言楼 共享教室 B',
      credits: 2, term: '第二学期 · 第 1—14 周',
      brief: '以英式议会制为主体，训练即兴立论、反驳与归纳。',
      content: [
        '论题分类与文献检索（前 4 周）；',
        '立论稿与反驳稿写作（中段 6 周）；',
        '模拟联合辩论赛（最后 4 周）。',
      ],
      midterm: { method: '现场辩论评估', content: '抽签分组进行 30 分钟即兴辩论，由教师与互评打分。' },
      finalExam: { method: '联合辩论赛 + 自评报告', content: '比赛成绩 70% + 1500 字英文自评 30%。' },
      remark: 'Whitman 老师有英式幽默，但对引用规范极严格；建议提前学 OSCOLA 引注。',
    },

    // —— 社团课 —— //
    {
      id: 'c-lit-craft', code: 'CLB-LIT-01', name: '文学部 · 创作工坊', kind: 'club', tone: 'wisteria',
      teacher: '雾岛 葵', teacherId: 'ch-aoi', assistant: '主人公（轮值）', assistantId: 'ch-mc',
      schedule: '周三 · 放学后 16:30—18:00',
      classroom: '旧馆图书室 · 西窗席',
      credits: 1, term: '第二学期 · 全期',
      brief: '以「写下与擦去」为主题的同人创作工坊，每周一题。',
      content: [
        '题型轮换：诗、短篇、片段、剧本片段、信件。',
        '每节末进行匿名互评（绿、黄、红三档）。',
        '期末汇编为本期文学部合本。',
      ],
      midterm: { method: '中期合稿审议', content: '提交两篇作品，部内全员讨论挑选合本入选稿。' },
      finalExam: { method: '合本印制与朗读会', content: '每位部员朗读自选作品，并撰写百字感想。' },
      remark: '此课只对文学部部员开放；旁听需提前一周向部长申请。',
    },
    {
      id: 'c-orch-ensemble', code: 'CLB-ORC-01', name: '交响乐团 · 室内合奏', kind: 'club', tone: 'amber',
      teacher: '一之濑 千夏', teacherId: 'ch-chinatsu', assistant: '黑泽 澪', assistantId: 'ch-mio',
      schedule: '周二 / 周五 · 放学后 17:00—19:00',
      classroom: '梧桐音乐厅',
      credits: 2, term: '第二学期 · 全期',
      brief: '为春樱演奏会准备的弦乐五重奏与管乐重奏团排练课。',
      content: [
        '基础发声、乐句呼吸训练；',
        '本期演出曲目逐段精排；',
        '彩排与录音回听。',
      ],
      midterm: { method: '中期试演', content: '选定的两段乐章公开演奏并由会长指挥讲评。' },
      finalExam: { method: '春樱演奏会现场', content: '正式演出即为期末考核，按演出表现综合评定。' },
      remark: '澪同学是中提琴小教官，能极快指出指法瑕疵；不要怕被她指正。',
    },
    {
      id: 'c-tea-omote', code: 'CLB-TEA-01', name: '清水茶道 · 表千家点前', kind: 'club', tone: 'moss',
      teacher: '若叶 凉子', teacherId: 'ch-ryouko', assistant: '——',
      schedule: '周四 · 放学后 15:30—17:30',
      classroom: '清水茶室',
      credits: 1, term: '第二学期 · 全期',
      brief: '正式由表千家流派传习的点前与客礼训练。',
      content: [
        '叠茶巾、收水、点茶等基础动作分解；',
        '客礼次第与对话礼节；',
        '茶事流程通排。',
      ],
      midterm: { method: '点前演示', content: '独立完成一次薄茶点前，全员评议姿势与节奏。' },
      finalExam: { method: '茶事正客', content: '担任正客或亭主完成一次完整茶事，由凉子前辈考核。' },
      remark: '请务必准时；茶釜烧开有节奏，迟到会让全场重等一轮。',
    },
    {
      id: 'c-photo-dark', code: 'CLB-PHT-01', name: '影像研究部 · 银盐工艺', kind: 'club', tone: 'ink',
      teacher: '汐见 优奈', teacherId: 'ch-yuuna', assistant: '若叶 凉子', assistantId: 'ch-ryouko',
      schedule: '周三 / 周五 · 放学后 16:00—18:00',
      classroom: '银盐暗房',
      credits: 1, term: '第二学期 · 第 3—14 周',
      brief: '从胶片装填、显影到放大的全流程银盐工艺训练。',
      content: [
        '中古机身的清洁与装片；',
        '显影液配比与温度控制；',
        '人像、风景两类放大试片。',
      ],
      midterm: { method: '作品评议', content: '提交三张自选放大作品并到场讲解。' },
      finalExam: { method: '联合展览', content: '与他校影研举办联合展览，按观众与教师双重投票评分。' },
      remark: '凉子前辈对显影液浓度有奇异的嗅觉直觉；遇到色差时务必先咨询她。',
    },

    // —— 特殊课 —— //
    {
      id: 'c-sp-archive', code: 'SPC-ARC-01', name: '档案馆 · 校史秘录研读', kind: 'special', tone: 'vermil',
      teacher: '大门 一郎（学园理事）', assistant: '黑泽 春树', assistantId: 'ch-haruki',
      schedule: '每月第二、四个周六 · 09:30—11:30',
      classroom: '档案馆 地下 A 区',
      credits: 1, term: '本学年 · 全年',
      brief: '面向被授予「档案通行徽」的少数学生开放，研读樱栖学园 1924 年至今的内部纪要。',
      content: [
        '学园编年史与重大事件复盘；',
        '历代学生会决议解析；',
        '部分被封缄文件的开启仪式（仅限有徽者参与）。',
      ],
      midterm: { method: '档案札记', content: '撰写一篇关于任一历史事件的札记，须基于一次手抄原件。' },
      finalExam: { method: '内部论坛', content: '在年终内部论坛上做 20 分钟报告，听众为理事会与会长。' },
      remark: '该课程的部分内容受保密协议约束；课堂之外不得讨论或外传。',
    },
    {
      id: 'c-sp-shrine', code: 'SPC-SHR-01', name: '神社 · 祭礼与祝词', kind: 'special', tone: 'sakura',
      teacher: '巫女 御园', assistant: '——',
      schedule: '每月初一、十五 · 06:00—07:30',
      classroom: '校园神社 · 拜殿',
      credits: 1, term: '本学年 · 全年',
      brief: '以学业之神奉祀传统为线，习练日本神道祭礼次第与基础祝词。',
      content: [
        '玉串奉奠、拍手礼、二礼二拍手一礼之分解；',
        '常用祝词背诵与诵读节奏；',
        '春秋两次例祭的实地担纲。',
      ],
      midterm: { method: '祝词背诵', content: '当面诵读指定祝词，节律与发声为主要评分点。' },
      finalExam: { method: '担当一次例祭', content: '于秋季例祭中担当一名实际职位，受御园指导评定。' },
      remark: '清晨课程；冬季会非常冷。请着深色和服或校服改良的式服出席。',
    },
    {
      id: 'c-sp-tutor', code: 'SPC-CHN-01', name: '会长导修 · 自治论与决策伦理', kind: 'special', tone: 'sakura',
      teacher: '一之濑 千夏', teacherId: 'ch-chinatsu', assistant: '——',
      schedule: '每周日 · 19:30—21:00（仅在线）',
      classroom: '钟楼天台 · 远程席（凭通行牌）',
      credits: 1, term: '第二学期 · 第 4—16 周',
      brief: '由学生会会长亲授的小班导修，研讨自治组织的决策伦理与权责边界。',
      content: [
        '近三年学生会决议复盘（每周一案）；',
        '罗尔斯式正义论与学园语境的对话；',
        '小型情景演练：作为会长你会如何裁决？',
      ],
      midterm: { method: '案例评议', content: '提交一份对历史决议的反思札记（1500 字以上）。' },
      finalExam: { method: '私席口试', content: '与会长面对面进行 30 分钟问答，主题随机抽取。' },
      remark: '本课程不公开开设。能修读者自然知道自己为何在此。',
    },
  ];

  return { facilities, organizations, characters, ruleDocs, formTemplates, formRecords, worldEntries, courses };
})();
