/* scripts/data.js — 樱丘大学世界档案 (与 init-variables.js 变量系统同步) */
window.GameData = (function () {

  // —— 设施 (13 处) —— //
  const facilities = [
    { id: 'fac-plaza', name: '学院广场', type: '公共', area: '正门内侧', desc: '樱丘大学主入口，铺有樱花色地砖，中央立着校训石碑。', tone: 'sakura',
      hours: '全时段开放', atmosphere: '风、樱、新生的喧闹', orgs: [], icon: 'flag' },
    { id: 'fac-media', name: '多媒体教学楼', type: '学术', area: '校园东区', desc: '配备最新投影与录播系统的现代化教学楼，理论课主场地。', tone: 'ink',
      hours: '周一至周六 07:00 — 21:00', atmosphere: '电子屏、空调、翻书声', orgs: [], icon: 'book' },
    { id: 'fac-multi', name: '多功能教学楼', type: '综合', area: '校园东区', desc: '含阶梯教室、研讨室与社团活动室，顶层为性爱部专用空间。', tone: 'wisteria',
      hours: '周一至周日 07:00 — 22:00', atmosphere: '木质地板、海报、乐声', orgs: ['org-sex-club'], icon: 'door-open' },
    { id: 'fac-gym', name: '室内体育馆', type: '运动', area: '校园北区', desc: '标准篮球场与可移动看台，周末常举办校内联赛。', tone: 'moss',
      hours: '周一至周日 06:00 — 22:00', atmosphere: '汗水、地板蜡、口哨', orgs: [], icon: 'activity' },
    { id: 'fac-pool', name: '室内游泳馆', type: '运动', area: '校园北区', desc: '恒温 28°C 标准泳道，游泳社专属训练场地，也用于水下性爱活动。', tone: 'moss',
      hours: '周一至周日 06:00 — 21:00', atmosphere: '氯、水声、回响', orgs: [], icon: 'water' },
    { id: 'fac-smallball', name: '小球馆', type: '运动', area: '校园北区', desc: '羽毛球社主场地，铺设专业防滑地胶，通风良好。', tone: 'amber',
      hours: '周一至周日 08:00 — 21:00', atmosphere: '球拍挥击、球鞋摩擦、记分牌翻动', orgs: [], icon: 'target' },
    { id: 'fac-admin', name: '行政楼', type: '行政', area: '校园中心', desc: '校方管理层与学生会所在地，一楼设保健室与医疗检测隔间。', tone: 'vermil',
      hours: '周一至周五 08:30 — 17:30', atmosphere: '打印机、文件夹、高跟鞋', orgs: ['org-student-council', 'org-health-room'], icon: 'building' },
    { id: 'fac-park', name: '学生公园', type: '休憩', area: '校园南区', desc: '草坪、樱花林与蜿蜒步道，午休时最热闹，傍晚则是情侣的私密空间。', tone: 'sakura',
      hours: '全时段开放', atmosphere: '草香、鸟鸣、私语', orgs: [], icon: 'leaf' },
    { id: 'fac-dorm', name: '学生公寓', type: '生活', area: '校园西区', desc: '六层公寓楼，单人间为主，配有公共浴室与自习室。程励行住 3 楼 307 室。', tone: 'wisteria',
      hours: '住宿生 24 小时', atmosphere: '洗衣液、泡面、深夜耳机', orgs: [], icon: 'home' },
    { id: 'fac-cafeteria', name: '食堂', type: '生活', area: '校园西区', desc: '两层大型食堂，一楼自助餐，二楼特色窗口，星野老师的家政课有时在此设实操。', tone: 'amber',
      hours: '07:00—09:00 / 11:30—13:30 / 17:00—19:30', atmosphere: '味增汤、油炸、不锈钢托盘', orgs: [], icon: 'coffee' },
    { id: 'fac-teacher-dorm', name: '教师公寓', type: '生活', area: '校园西区', desc: '独栋小楼，坂上老师与水川校医各居一层，星野老师住顶层。', tone: 'moss',
      hours: '住宿教师 24 小时', atmosphere: '安静、书卷、深夜咖啡', orgs: [], icon: 'home' },
    { id: 'fac-yuzuki', name: '夕月温泉馆', type: '校外', area: '樱丘路南 · 步行 10 分钟', desc: '三层木造温泉旅馆，表面是正经疗养场所，二楼以上提供隐秘色情按摩套餐。', tone: 'amber',
      hours: '10:00 — 次日 02:00', atmosphere: '硫磺、桧木、蒸腾水汽', orgs: ['org-yuzuki-onsen'], icon: 'flame' },
    { id: 'fac-clinic', name: '樱丘综合诊所', type: '校外', area: '樱丘路东 · 步行 15 分钟', desc: '高端私人医疗机构，表面提供精密体检，实则进行以医疗为名的榨精实验。', tone: 'vermil',
      hours: '09:00 — 19:00（急诊 24 小时）', atmosphere: '消毒水、乳胶、仪器蜂鸣', orgs: ['org-sakuraoka-clinic'], icon: 'shield' },
  ];

  // —— 组织 (5 个) —— //
  const organizations = [
    { id: 'org-student-council', name: '学生会', short: '学生会', tone: 'sakura', icon: 'school',
      lead: '维持秩序 · 分配资源 · 对外协调',
      desc: '樱丘大学最高学生自治机构，负责课程资源调配、社团管理与对外联络。会长绫濑雪乃以理性著称。',
      tagline: '秩序是知识之母。',
      facility: 'fac-admin',
      members: ['ch-ayase-yukino'],
      type: '校级机构',
      tags: ['行政楼二楼', '资源分配权', '特殊课程管理'],
      story: '会长室的窗户正对樱花林，每到四月便满目粉白。绫濑在那里独自听过无数次放学钟声。' },
    { id: 'org-health-room', name: '保健室', short: '保健室', tone: 'moss', icon: 'shield',
      lead: '体检 · 理疗 · 性健康管理',
      desc: '由校医水川冴子掌管，配备专业医疗设备与私密检查隔间，负责全校师生的生理健康管理。',
      tagline: '健康是欲望的前提。',
      facility: 'fac-admin',
      members: ['ch-mizukawa-saeko'],
      type: '职能部门',
      tags: ['行政楼一楼', '私密隔间', '每周体检'],
      story: '水川校医的听诊器从不离身。她能用冰凉的金属面判断出你是否紧张——以及你为何紧张。' },
    { id: 'org-sex-club', name: '性爱部', short: '性爱部', tone: 'vermil', icon: 'flame',
      lead: '探索 · 交流 · 实践',
      desc: '特殊实践型社团，以「探索性爱本质」为宗旨。拥有各类情趣道具、专用观测室与教学大床。顾问为坂上静香。',
      tagline: '知识没有禁区。',
      facility: 'fac-multi',
      members: ['ch-banshang-jingxiang', 'ch-ayase-yukino', 'ch-ying-xili', 'ch-xiyuansi-liuyi', 'ch-tongdao-kelian'],
      type: '社团',
      tags: ['多功能教学楼顶层', '观测室', '情趣道具库', '教学大床'],
      story: '部室的墙上挂着一幅字：「身体即书卷，实验即阅读」。那是坂上老师亲手所书。' },
    { id: 'org-yuzuki-onsen', name: '夕月温泉馆', short: '夕月', tone: 'amber', icon: 'flame',
      lead: '理疗 · 按摩 · 隐秘服务',
      desc: '三层木造温泉旅馆，老板娘汤原夕子以包容的温柔经营。一层为正经温泉，二层素股乳交，三层插入式性爱。',
      tagline: '热水融化一切，包括底线。',
      facility: 'fac-yuzuki',
      members: ['ch-tangyuan-xizi', 'ch-naixu', 'ch-jiecheng-meisui'],
      type: '校外组织',
      tags: ['三层服务', '技师制', '绝对禁止技师体内射精'],
      story: '夕子的冰牛奶总是刚好在客人泡完温泉时送到。奈绪说那是她用身体试出来的温度。' },
    { id: 'org-sakuraoka-clinic', name: '樱丘综合诊所', short: '樱诊所', tone: 'vermil', icon: 'shield',
      lead: '体检 · 采样 · 医疗研究',
      desc: '高端私人医疗机构，由主治医师神崎堇创立。以精密体检之名，行男性活体标本采集之实。',
      tagline: '一切为了医学，身体只是数据。',
      facility: 'fac-clinic',
      members: ['ch-shenqi-jin', 'ch-qiancang-yin', 'ch-wushilan-zaoji'],
      type: '校外组织',
      tags: ['精密体检', '活体标本', '医疗操作绝对服从', '前列腺/G点专项'],
      story: '神崎医生的金丝眼镜后是一双把人体看作数据集合的眼睛。听诊器在她手里不是诊断工具，是传感器。' },
  ];

  // —— 角色 (15 人：主角 + 14 NPC) —— //
  const characters = [
    { id: 'ch-cheng-lixing', name: '程励行', kana: 'CHENG Lixing', tone: 'ink', avatar: '程',
      age: 18, year: '大一', height: '178 cm',
      orgs: [],
      look: '干净利落的短发，戴一副银框眼镜。眼神里既有初来乍到的不安，也有仔细观察一切的冷静。',
      build: '中等身形，肩宽腰窄，久坐书桌前养出的清瘦中带着少年特有的挺拔。',
      wear: '樱丘大学男生制服 · 藏蓝西装外套 · 白衬衫 · 黑色长裤 · 左手腕一只旧电子表。',
      thoughts: '我是这所大学唯一的男性。这不是幸运，这是一个需要认真对待的变量。',
      relations: [
        { who: 'ch-ayase-yukino', label: '第一个打招呼的人', text: '她的眼神像在做实验记录。我被当成了一个观测对象——这让情况变得更复杂了。' },
        { who: 'ch-banshang-jingxiang', label: '性教育导师', text: '坂上老师看我的眼神像是看到了一个珍稀物种。这让我既紧张又好奇。' },
      ],
      special: '唯一男性身份使其成为全校女性的隐性焦点。左手无意识转笔的习惯。',
      tagline: '全校唯一的男生。这不是设定，这是变量的初始值。' },

    { id: 'ch-banshang-jingxiang', name: '坂上静香', kana: 'SAKAUE Shizuka', tone: 'amber', avatar: '坂',
      age: 30, year: '教师 · 生物部/性爱部顾问', height: '163 cm',
      orgs: [{ org: 'org-sex-club', role: '顾问教师' }],
      look: '成熟饱满的熟女面容，唇肉丰厚，眼神从容而温暖。紧绷的白衬衫下F杯的丰腴身段呼之欲出。',
      build: '163cm / F92 / 腰63 / 臀94。熟女体型，丰腴不臃肿，沉甸甸的双乳与圆润臀部是岁月赠予的资本。',
      wear: '紧身白衬衫（纽扣微开）· 黑色极短包臀裙 · 红色细带丁字裤 · 黑色细跟高跟鞋 · 黑色蕾丝吊带丝袜。',
      thoughts: '新来的男学生对全校而言都是一场实验。作为性教育教师，我有责任引导他——当然，也要观察他。',
      relations: [
        { who: 'ch-cheng-lixing', label: '观察对象', text: '他是樱丘大学第一例男性活体教学样本。我会亲自示范，也会亲自记录。' },
        { who: 'ch-ayase-yukino', label: '学生', text: '雪乃是最特别的学生——她把性爱当作学术课题，这既让我欣慰又让我有点担心。' },
      ],
      special: '在性教育课堂上专业严谨，私下却温柔且自慰常态。生物部指导学生时动作轻柔如抚花瓣。',
      tagline: '讲台上的她像翻开一本从未被阅读的书——每一页都令人无法移开目光。' },

    { id: 'ch-mizukawa-saeko', name: '水川冴子', kana: 'MIZUKAWA Saeko', tone: 'moss', avatar: '水',
      age: 29, year: '校医 · 保健室负责', height: '172 cm',
      orgs: [{ org: 'org-health-room', role: '负责校医' }],
      look: '冰山御姐，锐利眼神。唇线平直，极少微笑。172cm高挑身形配上极低体脂，如同一把出鞘的手术刀。',
      build: '172cm / D88 / 腰60 / 臀90。高挑紧致，体脂极低，马甲线分明，高翘健身臀是每周四次健身的成果。',
      wear: '宽大白大褂（敞开）· 白色运动短热裤 · 下体真空 · 灰色低度数连裤袜 · 运动跑鞋 · 锁骨下小痣。',
      thoughts: '唯一的男性标本会对保健室工作造成负担，但这也意味着难得的活体数据。评估他是我的责任。',
      relations: [
        { who: 'ch-cheng-lixing', label: '研究对象', text: '他是极其珍贵的活体男性样本。我会用体温计、听诊器和手指分别测量他的反应。' },
      ],
      special: '惜字如金，不闲聊。能凭触诊判断肌肉疲劳程度。擦多肉植物是唯一公开的私人爱好。',
      tagline: '她的沉默里藏着比听诊器更精确的判断。' },

    { id: 'ch-tangyuan-xizi', name: '汤原夕子', kana: 'YUHARA Yuuko', tone: 'amber', avatar: '汤',
      age: 31, year: '夕月温泉馆 · 老板娘', height: '162 cm',
      orgs: [{ org: 'org-yuzuki-onsen', role: '老板娘' }],
      look: '柔软丰盈的熟女面容，被岁月善待的温泉水汽般的女人。G杯巨乳把浴衣撑得岌岌可危，眼神慵懒而包容。',
      build: '162cm / G94 / 腰65 / 臀96。丰腴圆润的熟女身段，沉重下垂的双乳与肥圆宽大的臀部充满母性肉感。',
      wear: '宽松深蓝色浴衣（领口大开）· 内部完全真空 · 木屐。',
      thoughts: '即将到来的年轻男性技师让我久违地感到期待。奈绪已经迫不及待地想试他的手法了。',
      relations: [
        { who: 'ch-naixu', label: '搭档/恋人', text: '奈绪是我最完美的作品——从青涩的按摩学员到能与我配合天衣无缝的搭档。' },
      ],
      special: '泡后必喝冰牛奶。收藏了大量色情漫画与各地浴盐。清晨瑜伽是每日必修课。',
      tagline: '她像一池永远温热的泉水——你跳进去，就不想再上来。' },

    { id: 'ch-ayase-yukino', name: '绫濑雪乃', kana: 'AYASE Yukino', tone: 'sakura', avatar: '绫',
      age: 19, year: '大二 · 学生会会长', height: '163 cm',
      orgs: [
        { org: 'org-student-council', role: '会长' },
        { org: 'org-sex-club', role: '研究员' },
      ],
      look: '瓷器般白皙的肌肤，小巧唇形。脊背永远挺直，带着芭蕾气质的优雅。B杯的纤细处子之身透着高岭之花的清冷。',
      build: '163cm / B杯 / 纤细 / 关节小巧 / 锁骨清晰。笔直修长的双腿是长跑训练的成果，脚踝骨感而优美。',
      wear: '规整校服衬衫 · 藏青色百褶超短裙 · 纯白细带三角内裤 · 黑色乐福鞋 · 纯白蕾丝吊带丝袜 · 学生会臂章。',
      thoughts: '男生是学校实验的一环。我需要理性对待，但同时也不妨观察他作为个体的反应数据。',
      relations: [
        { who: 'ch-cheng-lixing', label: '观测对象', text: '他的到来是樱丘大学最重大的变量。作为会长，我需要记录这个实验的全过程。' },
        { who: 'ch-banshang-jingxiang', label: '导师', text: '坂上老师是少数能与我进行纯粹学术对话的人。她理解性爱作为一种知识体系的价值。' },
      ],
      special: '深夜独自听爵士乐。收集复古文具与旧钢笔。坚持长跑，风雨无阻。',
      tagline: '她把感情也当成论文题目——冷静地观察，谨慎地假设，然后在独处时推翻一切。' },

    { id: 'ch-ying-xili', name: '樱汐里', kana: 'SAKURA Shiori', tone: 'wisteria', avatar: '樱',
      age: 18, year: '大一 · 文学部/性爱部', height: '158 cm',
      orgs: [
        { org: 'org-sex-club', role: '部员' },
      ],
      look: '猫系娇小的文学少女，唇色浅淡，眼神柔弱而充满保护欲。A杯平胸与细长四肢构成极致的反差诱惑。',
      build: '158cm / A杯 / 纤瘦柔软。娇小身躯每一寸都透着惹人怜爱的脆弱，34码的小脚是全校最小的。',
      wear: '宽大旧式水手服衬衫 · 极短深色百褶裙 · 内部完全真空 · 黑色制服皮鞋 · 纯白蕾丝边过膝袜。',
      thoughts: '唯一的男生……想把他写进同人肉文里。也想鼓起勇气和他说一句话，就一句。',
      relations: [
        { who: 'ch-cheng-lixing', label: '暗恋/恐惧', text: '他看起来像从我写的故事里走出来的人。我不敢靠近他，但我会在纸上靠近他一百次。' },
        { who: 'ch-xiyuansi-liuyi', label: '学姐', text: '瑠衣学姐太美了，像小提琴的声音变成了人。和她同部让我每天都紧张。' },
      ],
      special: '自家经营旧书店，常在书架间一待就是一整天。私下用笔名发表同人肉文，已有固定读者群。',
      tagline: '她的笔比她的嘴勇敢一百倍——纸上全是她不敢说出口的欲望。' },

    { id: 'ch-naixu', name: '奈绪', kana: 'NAO', tone: 'amber', avatar: '奈',
      age: 22, year: '夕月温泉馆 · 专职技师', height: '160 cm',
      orgs: [{ org: 'org-yuzuki-onsen', role: '专职技师' }],
      look: '清纯温顺的面容，眉眼含春，容易害羞。D杯的饱满身材与清纯脸蛋形成强烈反差，穴口常年外翻泛着水光。',
      build: '160cm / D杯 / 苗条匀称 / 腰58 / 臀88。被彻底开发成淫娃的躯体，紧致白皙的大腿内侧藏着被频繁使用的痕迹。',
      wear: '浅色低胸技师制服 · 极细白色高叉丁字裤 · 肤色超薄防勾丝袜 · 软底拖鞋。',
      thoughts: '将服侍客人视为天职。按摩时的每一次触碰都是虔诚的仪式。私下渴望被粗暴对待。',
      relations: [
        { who: 'ch-tangyuan-xizi', label: '恩人/恋人', text: '夕子姐给了我一切——从按摩技法到身体的觉醒。我会用余生回报她。' },
      ],
      special: '舌头灵巧度惊人，精油调配有独家秘方。作为夕子培训的专属模特，对身体的控制力极强。',
      tagline: '她的清纯是真的，她的淫荡也是真的——两者从不矛盾。' },

    { id: 'ch-xiyuansi-liuyi', name: '西园寺瑠衣', kana: 'SAIONJI Rui', tone: 'wisteria', avatar: '瑠',
      age: 18, year: '大一 · 音乐社/性爱部', height: '167 cm',
      orgs: [
        { org: 'org-sex-club', role: '部员' },
      ],
      look: '宛如一枚成熟的果实，唇珠饱满，举止优雅沉静。D杯的挺拔高耸与纤细腰肢形成完美的沙漏曲线。',
      build: '167cm / D杯 / 匀称骨骼 / 腰60 / 臀89。大腿丰腴、小腿修长，骨骼匀称的饱满肉体在校服下勒出成熟曲线。',
      wear: '紧绷校服衬衫（微开第二颗纽扣）· 极短深灰包臀裙 · 黑色蕾丝细带三角裤 · 黑色高跟系带皮鞋 · 黑色半透明吊带丝袜。',
      thoughts: '新来的男生像一把未调音的大提琴——我想知道他是什么音色，能弹出怎样的声响。',
      relations: [
        { who: 'ch-cheng-lixing', label: '好奇', text: '他是一把还没被拉过的琴。我很好奇他的弦有多紧，音域有多宽。' },
        { who: 'ch-tongdao-kelian', label: '性爱部同僚', text: '桐岛的体能令人惊叹。我们一个是弦乐，一个是游泳——但在床上，节奏感是相通的。' },
      ],
      special: '大提琴独奏时习惯闭上眼睛。深夜独自听黑胶，收集古董乐器店的名片。讲究情调与前戏。',
      tagline: '她拉琴时闭眼，不是因为投入——是因为她想用触觉重新认识每一个音符。' },

    { id: 'ch-xingye-liumei', name: '星野留美', kana: 'HOSHINO Rumi', tone: 'amber', avatar: '星',
      age: 26, year: '教师 · 家政课', height: '155 cm',
      orgs: [],
      look: '温婉人妻气质，肌肤白里透红。娇小肉感的身躯透着极强的人妻韵味，情动时眼神迷离如醉。',
      build: '155cm / C杯 / 娇小柔软 / 蜜桃臀型。大腿内侧极多软肉，缝隙常年保持湿润泥泞，极易高潮体质。',
      wear: '紧身针织薄毛衣 · 外罩半透明围裙 · 极简系带开裆丁字裤（外部完全真空，围裙遮掩）· 肉色油亮高筒丝袜 · 浅口单鞋。',
      thoughts: '真实的男性肉体……隐藏的饥渴被点燃了。我一定要让他品尝我研制的催情料理。',
      relations: [
        { who: 'ch-cheng-lixing', label: '饥渴', text: '全校唯一的男生在我的家政课上。这是一个需要精心准备食材的场合。' },
        { who: 'ch-banshang-jingxiang', label: '同事', text: '坂上老师和我教的是不同层面的"身体知识"。我们偶尔交换教案。' },
      ],
      special: '研制催情香料与料理是毕生兴趣。私下收集微型情趣内衣，已拥有超过200件藏品。极易高潮，一次料理课可偷偷高潮多次。',
      tagline: '她的围裙下藏着一座秘密花园——而她是唯一的花匠。' },

    { id: 'ch-jiecheng-meisui', name: '结城美穗', kana: 'YUKI Miho', tone: 'vermil', avatar: '结',
      age: 31, year: '家庭主妇（夕月隐藏客源）', height: '166 cm',
      orgs: [{ org: 'org-yuzuki-onsen', role: 'VIP 客户（隐）' }],
      look: '雍容华贵的熟女面容，牛奶肌白得耀眼。F杯沉重白皙的双乳与96cm的宽大臀部是保养得当的极品雌性资本。',
      build: '166cm / F96 / 腰64 / 臀96。熟女体型，丰硕双乳乳晕呈深色，层层肉褶的下体是成熟女性的生理勋章。',
      wear: '真丝深V开衫 · 黑色高叉蕾丝三角内裤（无裙裤遮掩）· 黑色吊带网眼丝袜 · 细跟皮靴 · 闪亮钻戒。',
      thoughts: '丈夫常年出差，听说夕月即将有年轻男性技师。难耐的肉体隐隐作痛。',
      relations: [
        { who: 'ch-cheng-lixing', label: '幻想对象', text: '他是夕月的新人。年轻的身体比丈夫更能填补这些年的空缺——我只需要一个理由。' },
      ],
      special: '购买昂贵香水与内衣是唯一的生活乐趣。知道夕月隐藏服务的全部菜单。对年轻强壮无抵抗力。',
      tagline: '钻戒是戴给外人看的。她的身体只向年轻人敞开——那是丈夫永远买不到的服务。' },

    { id: 'ch-tongdao-kelian', name: '桐岛可怜', kana: 'KIRISHIMA Karen', tone: 'moss', avatar: '桐',
      age: 18, year: '大一 · 游泳社/性爱部', height: '165 cm',
      orgs: [
        { org: 'org-sex-club', role: '部员' },
      ],
      look: '阳光健康的面容，曲线分明的沙漏身材。蝴蝶骨与脊柱沟构成完美的背部风景，低体脂下马甲线分明。',
      build: '165cm / C杯 / 黄金比例 / 低体脂 / 腰56 / 臀86。紧实圆润的C杯胸与完美的蜜桃臀是每日晨泳的成果。',
      wear: '紧绷至极的短款运动背心（无内衣）· 极高叉连体竞速泳衣下半部分（三角款）· 纯白低度数半透丝袜 · 运动鞋 · 护腕。',
      thoughts: '唯一的男生！我想和他比赛，游泳也好床上也好，看看他的体能极限在哪里。',
      relations: [
        { who: 'ch-cheng-lixing', label: '竞争/好奇', text: '他是全校唯一的男性选手。我需要测试他的体能参数——在泳池里，也在床上。' },
      ],
      special: '晨泳训练从不间断。烤饼干的少女心与运动系的爆发力并存。把性行为视为一种体力运动。',
      tagline: '她的人生只有两种模式：训练和比赛。而性爱是两者的交叉点。' },

    { id: 'ch-shenqi-jin', name: '神崎堇', kana: 'KANZAKI Sumire', tone: 'vermil', avatar: '神',
      age: 26, year: '樱丘综合诊所 · 负责人/主治医师', height: '168 cm',
      orgs: [{ org: 'org-sakuraoka-clinic', role: '负责人/主治医师' }],
      look: '金丝眼镜后的锐利眼波，泪痣点缀冷肤色。薄冷的唇形与E杯的丰满肉体形成冰火两极的禁欲诱惑。',
      build: '168cm / E杯 / 高挑匀称 / 腰60 / 臀90。丰满圆挺的E杯、平坦且有轻微腹肌的腰腹、笔直修长的双腿——毫无赘肉的完美躯体。',
      wear: '紧身深V半透明白大褂（隐露乳沟）· 黑色开裆蕾丝吊带内裤 · 黑色极薄微透丝袜 · 黑色细高跟鞋 · 金丝眼镜。',
      thoughts: '程励行是极其珍贵的罕见活体男性标本。我迫不及待想测试他的勃起反射与精液质量。',
      relations: [
        { who: 'ch-cheng-lixing', label: '活体标本', text: '他是无价的男性样本。我会用听诊器、导尿管和我的身体分别获取他的数据。' },
      ],
      special: '听诊器从不离身。将性服务视为维持生命体征的必要医疗手段。研发的强效润滑剂是诊所的专利产品。',
      tagline: '在她眼里，你的每一次勃起都是一组待记录的数据——而她从不遗漏任何一个数据点。' },

    { id: 'ch-qiancang-yin', name: '浅仓音', kana: 'ASAKURA Oto', tone: 'sakura', avatar: '浅',
      age: 20, year: '樱丘综合诊所 · 体检护士', height: '156 cm',
      orgs: [{ org: 'org-sakuraoka-clinic', role: '体检护士' }],
      look: '双马尾、甜美笑容、粉嫩虎牙。元气活泼的面容配上C杯的挺拔身材，是诊所里最受欢迎的护士。',
      build: '156cm / C杯 / 娇小弹软 / 腰56 / 臀85。毫无防备的柔软腹部，极浅的粉色私处，小巧弹软的臀部。',
      wear: '超短款粉色半透护士服（领口大开）· 白色极细系带丁字裤 · 纯白蕾丝边过膝袜 · 白色厚底护士鞋 · 粉色护士帽。',
      thoughts: '真正的男人！我要用我的胸部给他做心电图的缓冲垫，抽血时也要多蹭几下。',
      relations: [
        { who: 'ch-cheng-lixing', label: '兴奋', text: '他是我的第一个真人男性患者！抽血、量血压、前列腺检查——每一个项目我都想亲自做。' },
      ],
      special: '抽血时胸部会不经意蹭到病人。容易自己先兴奋起来。把用身体安抚病人视为最棒的护理。',
      tagline: '她的笑容能让任何病人放松——但放松之后会发生什么，就超出护理手册的范围了。' },

    { id: 'ch-wushilan-zaoji', name: '五十岚早纪', kana: 'IGARASHI Saki', tone: 'vermil', avatar: '五',
      age: 22, year: '樱丘综合诊所 · 护士长', height: '162 cm',
      orgs: [{ org: 'org-sakuraoka-clinic', role: '护士长' }],
      look: '小恶魔眼角配上艳丽唇色，表面知心大姐姐的笑脸下藏着欺负人的坏心眼。E杯水滴形巨乳与丰腴大腿在护士服下呼之欲出。',
      build: '162cm / E杯 / 前凸后翘 / 腰59 / 臀88。微胖肉感的完美熟女身段，肥大的肉蒂与常年湿润的穴口是过度开发的证明。',
      wear: '紧绷深蓝色连体护士裙（下摆极短，拉链开至胸口）· 完全真空（无内裤）· 黑色开裆网眼丝袜 · 黑色护士高跟鞋 · 胸口听诊器。',
      thoughts: '终于来了个真正的男人。我已经在盘算着怎么在体检时用手指把他弄哭了——那声音一定很好听。',
      relations: [
        { who: 'ch-cheng-lixing', label: '玩具', text: '他是我的新玩具。我会在前列腺检查时故意按压敏感点，然后录下他的喘息声。' },
      ],
      special: '喜欢在做前列腺检查时故意按压敏感点。涂指甲油是每日仪式。私下听病人的喘息录音是隐秘爱好。',
      tagline: '她的温柔是一层糖衣——舔开之后，里面全是让人腿软的坏心眼。' },

    { id: 'ch-lin-xueye', name: '林雪野', kana: 'LIN Xueye', tone: 'ink', avatar: '林',
      age: 19, year: '大二', height: '168 cm',
      orgs: [],
      look: '齐肩黑发，眼神总是带着审视。淡粉色薄唇极少上扬，清冷距离感如同一块在阳光下不融的冰。',
      build: '168cm / B杯 / 清瘦高挑 / 腰57 / 臀86。极白的皮肤在阳光下近乎透明，笔挺的双腿没有一丝赘肉。',
      wear: '宽松白色无袖T恤 · 极短黑色百褶裙（内部完全真空）· 白色极薄过膝丝袜 · 白色平底单鞋 · 黑框防蓝光眼镜。',
      thoughts: '暂无。',
      relations: [],
      special: '讨厌别人弄乱她的书桌。对声音极其敏感，能分辨出十米外的翻书声。独来独往，看冷门哲学书。',
      tagline: '她不是冷漠，只是对大多数事物缺乏好奇——直到那个变量出现在她的视线里。' },
  ];

  // —— 规章文档 —— //
  const ruleDocs = [
    { id: 'doc-school-rule', name: '樱丘大学校规', version: 'v4.1',
      desc: '樱丘大学基础行为守则，常驻注入。',
      trigger: 'always', keywords: ['校规', '规定', '违规', '纪律'],
      injection: 'system', format: 'indent', maxDepth: 2,
      sections: [
        { id: 's1', title: '第一章 总则', children: [
          { id: 's1-1', kind: 'rule', text: '本校以「求真、自律、开放」为校训。知识没有禁区，身体亦然——但一切探索须建立在知情与自愿之上。' },
          { id: 's1-2', kind: 'rule', text: '校规未尽事宜，由学生会、保健室与性爱部三方联席会议共同议决。' },
          { id: 's1-3', kind: 'rule', text: '本校为日本文部科学省特批的单性别教育改革试点校。唯一男性学生的招收、培养与评估受本规则特别保护。' },
        ]},
        { id: 's2', title: '第二章 性别平等与特别条例', children: [
          { id: 's2-1', kind: 'rule', text: '男性学生在校期间享有与女性学生同等的学习权、隐私权与拒绝权。任何教学活动不得强制其参与非自愿的身体接触。' },
          { id: 's2-2', kind: 'rule', text: '所有涉及异性互动的教学与社团活动，须经参与双方明确同意，并在性爱部或保健室备案。口头同意即可生效，但事后任意一方可撤回。' },
          { id: 's2-3', kind: 'rule', text: '性教育课程（sex01—sex07）为全体学生必修学分。男性学生不得以任何理由申请免修，但可申请调整考核方式。' },
          { id: 's2-4', kind: 'rule', text: '男性学生每学期须接受保健室安排的基础体检至少一次。深度体检项目为选修，须另行签署同意书。' },
        ]},
        { id: 's3', title: '第三章 社团与部活', children: [
          { id: 's3-1', kind: 'rule', text: '加入新社团须经原社团许可与学生会备案。性爱部加入条件由该部自行制定，最低门槛为修完 sex01 课程。' },
          { id: 's3-2', kind: 'rule', text: '同时归属多组织者，不得使任一组织职责受影响。学生会会长兼任性爱部职务须向校方报备。' },
          { id: 's3-3', kind: 'rule', text: '社团活动不得与正常课程冲突。性爱部的社团活动（club01—club07）享有与正式课程同等的学分认定权。' },
        ]},
      ]},
    { id: 'doc-sex-ed-rules', name: '性教育课程管理条例', version: 'v2.3',
      desc: '性教育课程的课堂纪律与考核规范，关键词触发注入。',
      trigger: 'keyword', keywords: ['性教育', '课程', 'sex', '考核', '实操'],
      injection: 'after', format: 'indent', maxDepth: 3,
      sections: [
        { id: 'se1', title: '第一条 课堂纪律', children: [
          { id: 'se1-1', kind: 'rule', text: '理论课期间，学生须着校服或指定着装。实操课期间的着装要求由任课教师根据教学内容现场指定。' },
          { id: 'se1-2', kind: 'rule', text: '实操课中使用的情趣道具、医疗器械与教学设备均由学校统一采购与消毒。学生自备工具须经教师检查后方可使用。' },
          { id: 'se1-3', kind: 'rule', text: '课堂中发生的所有生理反应（勃起、润滑、高潮、射精等）均视为正常教学现象，不得因此嘲笑或羞辱任何学生。' },
        ]},
        { id: 'se2', title: '第二条 师生关系', children: [
          { id: 'se2-1', kind: 'rule', text: '任课教师在实操示范中与学生发生的身体接触，仅限于教学目的。超出教学范畴的私人关系不受本条例保护，但亦不禁止。' },
          { id: 'se2-2', kind: 'rule', text: '学生在课堂上对教师产生性欲或情感依恋属正常心理反应。鼓励通过保健室心理咨询或与教师直接沟通处理。' },
        ]},
        { id: 'se3', title: '第三条 考核与评估', children: [
          { id: 'se3-1', kind: 'rule', text: '每门课程设期中与期末两次考核。考核形式包括但不限于：假具测试、真人盲测、耐力赛、多人协作等。' },
          { id: 'se3-2', kind: 'rule', text: '男性学生作为全校唯一真人测试体，其身体状态直接影响全体学生的考核成绩。任何蓄意干扰其状态的行为视为作弊。' },
        ]},
      ]},
    { id: 'doc-yuzuki-rules', name: '夕月温泉馆服务规程', version: 'v1.8',
      desc: '温泉馆的三层服务标准与专属禁忌，关键词触发注入。',
      trigger: 'keyword', keywords: ['夕月', '温泉', '按摩', '套餐', '汤原', '奈绪'],
      injection: 'after', format: 'indent', maxDepth: 3,
      sections: [
        { id: 'yz1', title: '第一条 三层服务标准', children: [
          { id: 'yz1-1', kind: 'rule', text: '第一层「暧昧保健」：全身精油推拿，允许隔着浴衣进行肢体接触，禁触性器官。技师可着浴衣或技师制服。' },
          { id: 'yz1-2', kind: 'rule', text: '第二层「素股乳交」：允许胸部摩擦与大腿根部接触，可使用润滑液，允许射精在体外。技师须着丁字裤以上衣着。' },
          { id: 'yz1-3', kind: 'rule', text: '第三层「插入式性爱」：允许阴道插入与口交，不限体位。严禁在技师体内射精——此为夕月温泉馆最高禁忌。' },
        ]},
        { id: 'yz2', title: '第二条 技师权益', children: [
          { id: 'yz2-1', kind: 'rule', text: '技师可在服务中途叫停，无须说明理由。客人必须立即停止动作，否则将被永久列入黑名单。' },
          { id: 'yz2-2', kind: 'rule', text: '技师有权选择服务的最高层级。奈绪为三层全通技师，其他技师由老板娘汤原夕子根据培训进度逐级授权。' },
        ]},
        { id: 'yz3', title: '第三条 禁忌事项', children: [
          { id: 'yz3-1', kind: 'rule', text: '【绝对禁止】技师体内射精。违反者将被永久驱逐并通报樱丘大学学生会。' },
          { id: 'yz3-2', kind: 'rule', text: '禁止在温泉池水中进行第二、三层服务。水中的一切接触仅限于第一层保健推拿。' },
        ]},
      ]},
    { id: 'doc-clinic-rules', name: '樱丘综合诊所医疗同意书', version: 'v2.0',
      desc: '深度体检项目的知情同意条款，关键词触发注入。',
      trigger: 'keyword', keywords: ['诊所', '体检', '医疗', '神崎', '护士', '检查'],
      injection: 'after', format: 'indent', maxDepth: 3,
      sections: [
        { id: 'cl1', title: '第一条 体检项目分级', children: [
          { id: 'cl1-1', kind: 'rule', text: 'A 级（基础）：身高体重、血压心率、视力听力、血常规。无需签署同意书，由浅仓音护士执行。' },
          { id: 'cl1-2', kind: 'rule', text: 'B 级（深度）：前列腺触诊、精液分析、勃起反射测试、尿道敏感度评估。须签署本同意书，由五十岚早纪护士长执行。' },
          { id: 'cl1-3', kind: 'rule', text: 'C 级（科研）：多日连续采样、药物反应观测、极限榨取实验。须神崎堇医师亲自审批，仅向自愿参与者开放。' },
        ]},
        { id: 'cl2', title: '第二条 患者权利', children: [
          { id: 'cl2-1', kind: 'rule', text: '所有体检数据归患者本人所有。诊所仅保留用于医疗研究的匿名化副本。' },
          { id: 'cl2-2', kind: 'rule', text: '患者可在任意环节喊停。医疗操作绝对服从患者的最新指令——此条优先于「医疗操作绝对服从医师」之原则。' },
        ]},
        { id: 'cl3', title: '第三条 免责声明', children: [
          { id: 'cl3-1', kind: 'rule', text: '深度体检可能导致暂时性脱水、肌肉酸痛、阴茎敏感度短期下降。均在 24—48 小时内恢复。' },
          { id: 'cl3-2', kind: 'rule', text: 'C 级科研项目的参与者将获得学分补偿与樱丘诊所终身 VIP 资格。' },
        ]},
      ]},
  ];

  // —— 申请表 —— //
  const formTemplates = [
    {
      id: 'form-club-join', name: '社团加入申请表', code: 'CLUB_JOIN', version: 'v2.1',
      desc: '申请加入新社团时使用，需由原部长（如有）与学生会双重审批。',
      validityDays: 7,
      groups: [
        { id: 'g1', name: '基本信息', fields: [
          { id: 'f1', label: '申请人姓名', type: 'select', required: true, source: { kind: 'roster' }, placeholder: '从花名册选择' },
          { id: 'f2', label: '所在年级', type: 'text', required: true, placeholder: '如「大一」' },
          { id: 'f3', label: '申请日期', type: 'date', required: true },
        ]},
        { id: 'g2', name: '申请内容', fields: [
          { id: 'f4', label: '欲加入社团', type: 'select', required: true, source: { kind: 'organizations' }, placeholder: '选择社团' },
          { id: 'f5', label: '原社团（如有）', type: 'select', required: false, source: { kind: 'organizations' } },
          { id: 'f6', label: '申请理由', type: 'textarea', required: true, min: 30, max: 400, placeholder: '请用至少 30 字阐述加入意愿与可贡献之处。' },
        ]},
      ],
      flow: [
        { id: 's1', name: '原部长审查', who: '原所属部长（如不存在则跳过）', allowReject: true },
        { id: 's2', name: '目标社团面试', who: '目标社团负责人', allowReject: true },
        { id: 's3', name: '学生会备案', who: '学生会会长 / 书记', allowReject: true },
      ],
    },
    {
      id: 'form-sex-club-join', name: '性爱部入部特别申请', code: 'SEXCLUB_JOIN', version: 'v2.0',
      desc: '申请加入性爱部的专用表格。需额外提供性教育课程修读记录与身体自评。',
      validityDays: 14,
      groups: [
        { id: 'g1', name: '基本信息', fields: [
          { id: 'f1', label: '申请人姓名', type: 'select', required: true, source: { kind: 'roster' }, placeholder: '从花名册选择' },
          { id: 'f2', label: '已修性教育课程', type: 'text', required: true, placeholder: '如「sex01, sex03」' },
          { id: 'f3', label: '申请日期', type: 'date', required: true },
        ]},
        { id: 'g2', name: '身体自评', fields: [
          { id: 'f4', label: '是否已完成基础体检', type: 'radio', required: true, options: ['是', '否（需先预约保健室）'] },
          { id: 'f5', label: '性经验自述', type: 'textarea', required: true, min: 20, max: 300, placeholder: '请简述过往性经验（自慰/他人/器械），无经验可填写「无」。此为学术参考，不影响入部资格。' },
          { id: 'f6', label: '偏好部门', type: 'radio', required: false, options: ['观测组', '实操组', '数据记录组', '无偏好'] },
        ]},
        { id: 'g3', name: '知情确认', fields: [
          { id: 'f7', label: '我已知晓性爱部活动内容并自愿参加', type: 'radio', required: true, options: ['是，我自愿加入'] },
          { id: 'f8', label: '本人签字', type: 'text', required: true, placeholder: '请输入您的签名' },
        ]},
      ],
      flow: [
        { id: 's1', name: '保健室体检核查', who: '水川冴子校医', allowReject: true },
        { id: 's2', name: '性爱部面试', who: '坂上静香顾问 + 至少一名部员', allowReject: true },
        { id: 's3', name: '学生会备案', who: '绫濑雪乃会长', allowReject: true },
      ],
    },
    {
      id: 'form-yuzuki-booking', name: '夕月温泉馆服务预约表', code: 'YUZUKI_BOOK', version: 'v1.5',
      desc: '预约夕月温泉馆按摩套餐。第一层公开预约，第二、三层须到店后与技师面谈确认。',
      validityDays: 3,
      groups: [
        { id: 'g1', name: '预约信息', fields: [
          { id: 'f1', label: '预约人', type: 'select', required: true, source: { kind: 'roster' }, placeholder: '从花名册选择' },
          { id: 'f2', label: '预约日期', type: 'date', required: true },
          { id: 'f3', label: '期望时段', type: 'radio', required: true, options: ['上午 10:00—12:00', '下午 13:00—17:00', '晚间 18:00—22:00', '深夜 22:00—01:00'] },
        ]},
        { id: 'g2', name: '服务偏好', fields: [
          { id: 'f4', label: '期望技师', type: 'select', required: false, source: { kind: 'roster' }, placeholder: '可选（汤原夕子 / 奈绪）' },
          { id: 'f5', label: '本次最高接受层级', type: 'radio', required: true, options: ['仅第一层（暧昧保健）', '可接受第二层（素股乳交）', '开放第三层（插入式性爱）'] },
          { id: 'f6', label: '特殊需求', type: 'textarea', required: false, max: 200, placeholder: '如精油偏好、敏感部位回避、音乐选择等。' },
        ]},
        { id: 'g3', name: '确认', fields: [
          { id: 'f7', label: '我已阅读并理解《夕月温泉馆服务规程》', type: 'radio', required: true, options: ['是'] },
          { id: 'f8', label: '我理解「绝对禁止技师体内射精」规则', type: 'radio', required: true, options: ['我理解并同意'] },
        ]},
      ],
      flow: [
        { id: 's1', name: '温泉馆确认', who: '汤原夕子 / 奈绪', allowReject: true },
        { id: 's2', name: '到店面谈', who: '指定技师与客人当面确认', allowReject: true },
      ],
    },
    {
      id: 'form-clinic-consent', name: '樱丘综合诊所深度体检同意书', code: 'CLINIC_DEEP', version: 'v2.1',
      desc: '签署本同意书以授权进行 B 级及以上深度体检项目。',
      validityDays: 30,
      groups: [
        { id: 'g1', name: '受检者信息', fields: [
          { id: 'f1', label: '受检人姓名', type: 'select', required: true, source: { kind: 'roster' }, placeholder: '从花名册选择' },
          { id: 'f2', label: '最近一次性行为距今', type: 'text', required: true, placeholder: '如「3 天前」或「暂无」' },
          { id: 'f3', label: '当前是否有性器官不适', type: 'radio', required: true, options: ['无不适', '轻微不适', '有明显症状（请描述）'] },
        ]},
        { id: 'g2', name: '体检项目选择', fields: [
          { id: 'f4', label: '申请体检等级', type: 'radio', required: true, options: ['B 级（深度体检）', 'C 级（科研项目，需神崎医师审批）'] },
          { id: 'f5', label: '可接受的采样方式（多选）', type: 'text', required: true, placeholder: '如「前列腺触诊、精液采集、尿道探入」' },
          { id: 'f6', label: '过敏史与禁忌', type: 'textarea', required: false, max: 200, placeholder: '如对乳胶过敏、麻醉禁忌、敏感部位等。' },
        ]},
        { id: 'g3', name: '知情同意', fields: [
          { id: 'f7', label: '我已知晓体检内容并同意配合', type: 'radio', required: true, options: ['是，我同意'] },
          { id: 'f8', label: '本人（或监护人）签字', type: 'text', required: true, placeholder: '请输入您的签名' },
        ]},
      ],
      flow: [
        { id: 's1', name: '护士长预审', who: '五十岚早纪护士长', allowReject: false },
        { id: 's2', name: '医师审批（仅 C 级）', who: '神崎堇主治医师', allowReject: true },
        { id: 's3', name: '体检排期', who: '浅仓音护士', allowReject: false },
      ],
    },
  ];

  // —— 申请记录 —— //
  const formRecords = [
    { id: 'rec-1', tplId: 'form-club-join', who: 'ch-cheng-lixing', applied: '2026-04-08 09:00', status: 'pending', currentStep: 1,
      brief: '申请加入「性爱部」，作为唯一男性成员的入学必修体验。' },
  ];

  // —— 世界条目 (适配樱丘大学) —— //
  const worldEntries = [
    { id: 'we-1', name: '学院广场 · 正门', tag: '场景', body: '樱花色地砖铺就的广场，校训石碑刻着「求真、自律、开放」。程励行每天从这里开始和结束。' },
    { id: 'we-2', name: '绫濑会长', tag: '人物', body: '黑发低马尾、学生会臂章。她的理性是最坚固的铠甲——也是最脆弱的。' },
    { id: 'we-3', name: '坂上老师', tag: '人物', body: 'F杯熟女身段，在性教育讲台上专业而从容。私下是一杯温热的茶。' },
    { id: 'we-4', name: '性爱部活动日', tag: '事件', body: '每周三放学后，多功能教学楼顶层。今天是实操观摩课。' },
    { id: 'we-5', name: '夕月温泉馆套餐', tag: '提示', body: '第一层暧昧保健，第二层素股乳交，第三层插入式性爱。绝对禁止技师体内射精。' },
    { id: 'we-6', name: '樱丘综合诊所', tag: '提示', body: '表面是高端体检机构。内部医疗协议要求患者绝对服从医师指令。' },
  ];

  // —— 课程列表 (14 门：7 必修 + 7 社团) —— //
  const courses = [
    // ── 必修课程 (sex01—sex07) ──
    { id: 'c-sex01', code: 'sex01', name: '基础手交与阴茎勃起反射', kind: 'public', tone: 'vermil',
      teacher: '坂上静香', teacherId: 'ch-banshang-jingxiang', assistant: '程励行', assistantId: 'ch-cheng-lixing',
      schedule: '周一 · 第 3—4 节（10:30—12:00）', classroom: '多媒体教学楼 201 教室', credits: 2, term: '第二学期 · 第 1—16 周',
      varKey: '课程01',
      brief: '了解男性勃起海绵体的充血机制与系带神经敏感区。坂上静香亲自在讲台上对程励行进行手交示范。',
      content: [
        '第 1—2 周：男性外生殖器解剖学基础。',
        '第 3—6 周：握力、套弄频率与射精控制的生理机制。',
        '第 7—10 周：假具抗疲劳测试——使用指定手法让压力传感器达到规定数值。',
        '第 11—16 周：真人盲测激发——蒙眼状态下，仅凭手部触感在十分钟内完成勃起并射精。',
      ],
      midterm: { method: '假具抗疲劳测试', content: '使用指定手法让假具内的压力传感器达到规定数值。' },
      finalExam: { method: '真人盲测激发', content: '蒙眼状态下，仅凭手部触感让程励行在十分钟内勃起并射精。' },
      remark: '基础生理实操课，由坂上老师亲自示范引导。本课程为后续所有性教育课程的先修条件。' },

    { id: 'c-sex02', code: 'sex02', name: '临床色情理疗与生殖器保养', kind: 'public', tone: 'moss',
      teacher: '水川冴子', teacherId: 'ch-mizukawa-saeko', assistant: '——',
      schedule: '周二 · 第 5—6 节（13:30—15:00）', classroom: '行政楼一楼 · 保健室隔间', credits: 2, term: '第二学期 · 第 1—16 周',
      varKey: '课程02',
      brief: '学习人体性敏感带分布、淋巴排毒与前列腺液代谢原理。纯色情按摩，无性交插入。',
      content: [
        '第 1—4 周：男性性感带图谱绘制——从耳后到会阴的完整神经敏感区。',
        '第 5—8 周：前列腺体外按压与淋巴引流手法。',
        '第 9—12 周：外阴与腹部按压——在规定时间内引导射精。',
        '第 13—16 周：综合理疗实操——全身精油按摩与生殖器深度保养。',
      ],
      midterm: { method: '敏感点图谱绘制', content: '准确找到并按压伴侣的五个隐藏敏感穴位。' },
      finalExam: { method: '无接触高潮理疗', content: '通过外阴与腹部按压，在规定时间内引导程励行射精。' },
      remark: '水川校医的听诊器全程参与。课程中收集的所有生理数据记入学生健康档案。' },

    { id: 'c-sex03', code: 'sex03', name: '吞咽生理与深度口交技巧', kind: 'public', tone: 'amber',
      teacher: '星野留美', teacherId: 'ch-xingye-liumei', assistant: '程励行', assistantId: 'ch-cheng-lixing',
      schedule: '周三 · 第 3—4 节（10:30—12:00）', classroom: '多功能教学楼 102 家政教室', credits: 2, term: '第二学期 · 第 1—16 周',
      varKey: '课程03',
      brief: '咽喉黏膜抗压、干呕反射抑制与唾液腺分泌控制。星野留美进行深喉吞咽与舌尖打圈示范。',
      content: [
        '第 1—3 周：口腔与咽喉解剖生理学。',
        '第 4—7 周：冰火交替含咬测试——口腔含冰水或热水，对测力假具进行持续五分钟的稳定吸吮。',
        '第 8—12 周：干呕反射抑制训练与深喉进阶。',
        '第 13—16 周：咽喉排精承接——将程励行阴茎完全吞入喉部深处并承接其射精。',
      ],
      midterm: { method: '冰火交替含咬测试', content: '口腔含冰水或热水，对测力假具进行持续五分钟的稳定吸吮。' },
      finalExam: { method: '咽喉排精承接', content: '将程励行阴茎完全吞入喉部深处并承接其射精。' },
      remark: '星野老师研制的催情香料将在部分课时作为辅助教学工具使用。注意：本课程含吞咽练习，课后提供漱口水与喉糖。' },

    { id: 'c-sex04', code: 'sex04', name: '胸部摩擦与体脂缓冲动力学', kind: 'public', tone: 'amber',
      teacher: '汤原夕子 (客座)', teacherId: 'ch-tangyuan-xizi', assistant: '程励行', assistantId: 'ch-cheng-lixing',
      schedule: '周四 · 第 5—6 节（13:30—15:00）', classroom: '夕月温泉馆 · 二楼理疗室', credits: 2, term: '第二学期 · 第 5—16 周',
      varKey: '课程04',
      brief: '乳房脂肪厚度对男性肉体产生的包裹感与摩擦系数分析。G杯的汤原夕子将肉棒夹入乳沟示范素股乳交。',
      content: [
        '第 5—6 周：乳房解剖学与脂肪分布类型学。',
        '第 7—9 周：乳沟夹持抗阻——仅用胸部力量夹住运转中的震动棒十分钟不脱落。',
        '第 10—13 周：不同罩杯的摩擦系数对比实验。',
        '第 14—16 周：真人乳交榨精——利用胸部将程励行逼至高潮，期间严禁手部与口腔触碰。',
      ],
      midterm: { method: '乳沟夹持抗阻', content: '仅用胸部力量夹住运转中的震动棒十分钟不脱落。' },
      finalExam: { method: '真人乳交榨精', content: '利用胸部将程励行逼至高潮，期间严禁手部与口腔触碰。' },
      remark: '本课程在夕月温泉馆授课，由汤原夕子担任客座讲师。课堂环境为日式榻榻米，请注意着装要求。' },

    { id: 'c-sex05', code: 'sex05', name: '足底神经刺激与下肢力量控制', kind: 'public', tone: 'moss',
      teacher: '水川冴子', teacherId: 'ch-mizukawa-saeko', assistant: '程励行', assistantId: 'ch-cheng-lixing',
      schedule: '周五 · 第 1—2 节（08:30—10:00）', classroom: '室内体育馆 · 柔道室', credits: 2, term: '第二学期 · 第 3—16 周',
      varKey: '课程05',
      brief: '足弓骨骼结构、脚趾灵活性与男性下体受压安全阈值。水川冴子用修长有力的双足进行足交示范。',
      content: [
        '第 3—4 周：足部骨骼与肌肉解剖学。',
        '第 5—8 周：脚趾灵活性训练与力道控制系统。',
        '第 9—13 周：盲眼器械剥离——仅用双足将假具上的指定结构剥离且不触发超压警报。',
        '第 14—16 周：纯足部刺激排精——双臂固定，仅用双足与丝袜材质将程励行伺候至射精。',
      ],
      midterm: { method: '盲眼器械剥离', content: '仅用双足将剥离假具上的指定结构且不触发超压警报。' },
      finalExam: { method: '纯足部刺激排精', content: '将程励行双臂固定，学生仅用双足与丝袜材质将其伺候至射精。' },
      remark: '水川老师的灰色连裤袜是本课程的标准教学装备。学生自备丝袜须经教师审核材质。' },

    { id: 'c-sex06', code: 'sex06', name: '韵律同步与双修性交学', kind: 'public', tone: 'sakura',
      teacher: '坂上静香', teacherId: 'ch-banshang-jingxiang', assistant: '西园寺瑠衣', assistantId: 'ch-xiyuansi-liuyi',
      schedule: '周三 · 第 7—8 节（15:30—17:00）', classroom: '性爱部专用观测室', credits: 3, term: '第二学期 · 第 5—16 周',
      varKey: '课程06',
      brief: '学习微汗状态下内啡肽分泌机制及呼吸与骨盆摆动频率的同步技巧。在舒缓音乐中保持插入状态进行慢节奏瑜伽律动。',
      content: [
        '第 5—7 周：性交生理学——内啡肽、催产素与心率同步机制。',
        '第 8—10 周：骨盆摆动频率训练与呼吸同步。',
        '第 11—14 周：两人保持结合状态进行十五分钟的舒缓律动测试。',
        '第 15—16 周：共同高潮演练——频率同调，在深情拥吻中完成同时高潮射精。',
      ],
      midterm: { method: '呼吸同步测试', content: '两人保持结合状态进行十五分钟的舒缓律动。' },
      finalExam: { method: '共同高潮演练', content: '女生需引导程励行达到频率同调，在深情拥吻中完成同时高潮射精。' },
      remark: '摒弃极限压榨，注重男女互相配合与感官享受。西园寺同学将用大提琴的节奏感辅助教学。' },

    { id: 'c-sex07', code: 'sex07', name: '异性交媾实战综合演练', kind: 'public', tone: 'vermil',
      teacher: '全体指导教师', teacherId: '', assistant: '——',
      schedule: '周六 · 第 1—4 节（08:30—12:00）', classroom: '性爱部观测室 · 大床区', credits: 4, term: '第二学期 · 第 8—16 周',
      varKey: '课程07',
      brief: '总结各部位技巧，学习异性交媾的体位发力技巧与受孕概率规避。樱丘大学顶级实操课，汇聚所有技巧的最终考核。',
      content: [
        '第 8—9 周：体位分类学——从传教士到背后位的力学分析。',
        '第 10—11 周：车轮战耐久测试——程励行与三名不同体型的顶尖学生完成实质性插入并保持勃起。',
        '第 12—14 周：多对一实战——程励行与多名指导老师同时进行多对一实战。',
        '第 15—16 周：综合考核与毕业仪式。',
      ],
      midterm: { method: '车轮战耐久测试', content: '程励行需与三名不同体型的顶尖学生完成实质性插入并保持勃起。' },
      finalExam: { method: '教师团深度测评', content: '程励行需与多名指导老师同时进行多对一的实战做爱。' },
      remark: '本课程为樱丘大学性教育体系的毕业关卡。满分学生将被授予「性爱实践」荣誉学分。' },

    // ── 社团课程 (club01—club07) ──
    { id: 'c-club01', code: 'club01', name: 'Club 01 催情膳食与药理交媾观测', kind: 'club', tone: 'amber',
      teacher: '坂上静香 (联合指导)', teacherId: 'ch-banshang-jingxiang', assistant: '——',
      schedule: '周四 · 放学后 16:30—18:30', classroom: '多功能教学楼 102 家政教室', credits: 1, term: '第二学期 · 全期',
      varKey: '课程08',
      brief: '探讨催情香料与特制膳食对生殖器充血度的催化作用。星野留美喂食催情料理，水川冴子记录数据，部员依次提供深喉口交与乳交后插入。',
      content: ['催情香料药理学', '料理与生理反应同步观测', '部员轮流实操体验'],
      midterm: { method: '无', content: '社团活动不考核' },
      finalExam: { method: '无', content: '社团活动不考核' },
      remark: '结合食疗与药理的纯享性爱派对。星野老师的催情料理是全场主角。' },

    { id: 'c-club02', code: 'club02', name: 'Club 02 商业级色情侍奉与深度插入实战', kind: 'club', tone: 'amber',
      teacher: '汤原夕子 (联合指导)', teacherId: 'ch-tangyuan-xizi', assistant: '——',
      schedule: '周五 · 放学后 17:00—19:00', classroom: '夕月温泉馆 · 三楼 VIP 室', credits: 1, term: '第二学期 · 全期',
      varKey: '课程09',
      brief: '学习风俗业的高阶服务标准。汤原夕子与奈绪演示温泉馆三层套餐：推拿→素股乳交→插入式性爱。',
      content: ['日式按摩基础', '素股与乳交的商用技法', '真实插入的节奏与呼吸'],
      midterm: { method: '无', content: '社团活动不考核' },
      finalExam: { method: '无', content: '社团活动不考核' },
      remark: '从前戏推拿到真实插入一条龙的高级侍奉体验。严格遵守夕月温泉馆专属规则。' },

    { id: 'c-club03', code: 'club03', name: 'Club 03 水下失重状态核心掌控与深插演练', kind: 'club', tone: 'moss',
      teacher: '坂上静香 (联合游泳社)', teacherId: 'ch-banshang-jingxiang', assistant: '桐岛可怜', assistantId: 'ch-tongdao-kelian',
      schedule: '周二 · 放学后 17:00—19:00', classroom: '室内游泳馆', credits: 1, term: '第二学期 · 全期',
      varKey: '课程10',
      brief: '分析水下浮力对男女体位重心的影响。浅水区站立，利用浮力进行高难度水下骑乘与多角度深插。',
      content: ['水下浮力与体位力学', '水中呼吸同步', '多角度深插实操'],
      midterm: { method: '无', content: '社团活动不考核' },
      finalExam: { method: '无', content: '社团活动不考核' },
      remark: '利用水体浮力解锁高难度实战体位。桐岛同学的游泳体能是全场最大看点。' },

    { id: 'c-club04', code: 'club04', name: 'Club 04 赛后乳酸堆积与高心率催化交合', kind: 'club', tone: 'moss',
      teacher: '坂上静香 (联合羽毛球社)', teacherId: 'ch-banshang-jingxiang', assistant: '——',
      schedule: '周一 · 放学后 16:30—18:30', classroom: '小球馆', credits: 1, term: '第二学期 · 全期',
      varKey: '课程11',
      brief: '验证剧烈运动后高心率状态对性欲阈值的催化作用。利用亢奋的心肺状态进行高强度摩擦后直接插入式性交。',
      content: ['运动后生理状态分析', '高心率下的性欲阈值', '赛后直接交合实操'],
      midterm: { method: '无', content: '社团活动不考核' },
      finalExam: { method: '无', content: '社团活动不考核' },
      remark: '赛后高心率状态下的激情交合。运动产生的乳酸与内啡肽是最天然的催情剂。' },

    { id: 'c-club05', code: 'club05', name: 'Club 05 纪律压迫感与情境羞耻交媾', kind: 'club', tone: 'vermil',
      teacher: '坂上静香 (联合学生会)', teacherId: 'ch-banshang-jingxiang', assistant: '绫濑雪乃', assistantId: 'ch-ayase-yukino',
      schedule: '周五 · 放学后 16:30—18:30', classroom: '行政楼二楼 · 学生会室', credits: 1, term: '第二学期 · 全期',
      varKey: '课程12',
      brief: '探究阶级压迫、公开审查对女性快感中枢的刺激。风纪委员对程励行进行违纪搜身后撕开伪装进行背德插入实战。',
      content: ['权力关系与性心理学', '审查情境的羞耻催化', '背德插入实战'],
      midterm: { method: '无', content: '社团活动不考核' },
      finalExam: { method: '无', content: '社团活动不考核' },
      remark: '结合权力压迫与公开露出心理的背德性爱活动。绫濑会长的参与让情境更具真实感。' },

    { id: 'c-club06', code: 'club06', name: 'Club 06 假具戒断与真实肉体适应性实战', kind: 'club', tone: 'vermil',
      teacher: '坂上静香', teacherId: 'ch-banshang-jingxiang', assistant: '程励行', assistantId: 'ch-cheng-lixing',
      schedule: '周三 · 放学后 16:30—18:30', classroom: '性爱部观测室', credits: 1, term: '第二学期 · 第 6—16 周',
      varKey: '课程13',
      brief: '纠正长期使用机械震动带来的神经脱敏。上交所有假具，排队接纳程励行的真实插入，完全依靠阴道收缩与男性抽插达到高潮。',
      content: ['机械脱敏理论', '真实插入的神经适应', '排队实战训练'],
      midterm: { method: '无', content: '社团活动不考核' },
      finalExam: { method: '无', content: '社团活动不考核' },
      remark: '戒断对机械的依赖，回归纯粹的异性交配。本课程要求参与者上交所有个人情趣玩具。' },

    { id: 'c-club07', code: 'club07', name: 'Club 07 女性群交配合与体液涂抹洗礼', kind: 'club', tone: 'vermil',
      teacher: '坂上静香', teacherId: 'ch-banshang-jingxiang', assistant: '——',
      schedule: '周六 · 放学后 14:00—17:00', classroom: '性爱部观测室 · 大床区', credits: 1, term: '第二学期 · 第 8—16 周',
      varKey: '课程14',
      brief: '训练多名女性共享同一名男性时的部位分配与节奏配合。四到五名女生同时覆盖程励行的躯体，射精后精液被收集互相涂抹按摩。',
      content: ['多人配合的部位分配', '节奏同步训练', '体液收集与涂抹仪式'],
      midterm: { method: '无', content: '社团活动不考核' },
      finalExam: { method: '无', content: '社团活动不考核' },
      remark: '展现绝对数量优势下的女性共享性爱。精液涂抹按摩是课程的仪式性环节。' },
  ];

  return { facilities, organizations, characters, ruleDocs, formTemplates, formRecords, worldEntries, courses };
})();
